version: "3.7"
services:
  database:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dsgw
      POSTGRES_PASSWORD: dsgw
  flyway:
    build:
      ../database
    environment:
      HOST: database
    depends_on:
      - database
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      SERVICES: sns,sqs,lambda
      DOCKER_HOST: unix:///var/run/docker.sock
      DEBUG: "1"
      LAMBDA_REMOTE_DOCKER: "false"
      HOST_TMP_FOLDER: /tmp/localstack
      LAMBDA_REMOVE_CONTAINERS: "false"
      HOSTNAME_FROM_LAMBDA: localstack
      LAMBDA_DOCKER_NETWORK: local_default
    volumes:
      - /tmp/localstack:/tmp/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
  aws_setup:
    build:
      ./aws_setup/
    env_file:
      - ./aws_setup/.env
    environment:
      AWS_HOST: localstack
      AWS_PORT: 4566
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    volumes:
      - type: bind
        source: ./lambda
        target: /aws/lambda
    depends_on:
      - localstack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.13.3
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200