spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dsgw
    password: dsgw

server:
  port: 8081

aws:
  sns:
    endpoint:
      service-endpoint: http://localhost:4566
  sqs:
    endpoint:
      service-endpoint: http://localhost:4566
    processing:
      queues:
        order-actions:
          queue-name: order-actions
          poll-interval: 1s
          max-number-of-messages: 10
          wait-time-seconds: 5s
          message-attribute-names:
            - RequestID
            - ResponseQueueURL
          worker-pool:
            thread-count: 1
dsgw:
  events:
    order-event-topic-arn: arn:aws:sns:us-east-1:000000000000:order-events
