spring:
  profiles:
    active: local
  datasource:
    username: dsgw
  jackson:
    default-property-inclusion: non_absent

dsgw:
  auth:
    url-patterns:
      - /graphql

server:
  servlet:
    context-path: /api

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    me.kolek: DEBUG