DO $DO$
    BEGIN
        IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = 'dsgw_ro') THEN
            CREATE ROLE dsgw_ro;
        END IF;

        IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = 'dsgw_rw') THEN
            CREATE ROLE dsgw_rw;
        END IF;

        IF NOT EXISTS(SELECT 1 FROM pg_roles WHERE rolname = 'dsgwapp') THEN
            CREATE ROLE dsgwapp;
            GRANT dsgw_rw to dsgwapp;
        END IF;
    END;
$DO$;

ALTER SCHEMA public OWNER TO dsgw;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT ALL ON SCHEMA public TO dsgw;
REVOKE ALL ON SCHEMA public FROM dsgw_ro;
GRANT USAGE ON SCHEMA public TO dsgw_ro;
REVOKE ALL ON SCHEMA public FROM dsgw_rw;
GRANT USAGE ON SCHEMA public TO dsgw_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON TABLES TO dsgw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON TABLES FROM dsgw_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON TABLES TO dsgw_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON TABLES FROM dsgw_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT INSERT, SELECT, UPDATE, DELETE ON TABLES TO dsgw_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON SEQUENCES TO dsgw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON SEQUENCES FROM dsgw_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT SELECT ON SEQUENCES to dsgw_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON SEQUENCES FROM dsgw_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES to dsgw_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT ALL ON FUNCTIONS TO dsgw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON FUNCTIONS FROM dsgw_ro;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    REVOKE ALL ON FUNCTIONS FROM dsgw_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
    GRANT EXECUTE ON FUNCTIONS to dsgw_rw;